version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean install
    post-build:
      commands:
        - echo Build completed successfully
artifacts:
  files:
    -web/target/*.jar
    -scripts/*.sh
    -appspec.yml
  discard-paths: yes