# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - amazing-store-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: amazing-store  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace.web }} # set this to the path to your web app project
  JAVA_VERSION: '11'                # set this to the Java version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app


jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build with Maven
        run: mvn clean install and mvn compiler:compiler and mvn org.apache.maven.plugins:maven-compiler-plugin:compile and mvn org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile &
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'amazing-store-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2DB5304BA931432E99DE0A3F9BD9A54F }}
          package: '*.jar'